### PR TITLE
add japanese.js & hindi.js

### PR DESCRIPTION
**Pull request by ryan-b-writin**
"babbler.js" has been removed, and "japanese.js" & "hindi.js" have been created. both of these files contain an iife- with a lexicon object and a translateTo function. 

translateToJapanese() accepts a string and outputs a translated string. 

any repeated words in the string will only be translated once, possibly something to fix later.

### CODE REVIEW

**Comment by dupender** [comment]
:+1:  LOOks good

**Comment by zoeames** [comment]
just a reminder - according to the directions EACH member of our group needs to be contributing their OWN language to the translator.  in this PR you have both Hindi and Japanese.  Each other member of your team still needs to submit a language

**Comment by ryan-b-writin** [comment]
Zoe- Dhru and I met in person and pair-coded both languages together. I did the typing so I pushed it from my branch.

**Comment by ryan-b-writin** [comment]
@zoeames- Dhru and I met in person and pair-coded both languages. is it ok that i pushed them both from my branch since I did the typing?

**Comment by zoeames** [comment]
@ryan-b-writin yay pair programming!!  thats fine then.  next time just put that in the commit message so us stalkers know whats going on!   Also @dupender make sure you get a branch/feature in tomorrow - we want everyone to have actual git commit contributions to every group project

**Comment by dupender** [comment]
Zoe,

Yeah, Ryan and I met for 3 hrs yesterday, reviewed the assignment, went
through Steve Brownlee video and Ryan entered the code on his machine - I
really gained a better understanding of iifes, etc......but thanks for
checking up on us & keeping us on task!

Ryan, should I do the HTML or another language then?  I think Gayla may
have already started the HTML and Bradley may already be working on the
interacting js file.....?  I guess I can just code it tomorrow morning.

Dhru

**Comment by GAylabea** [comment]
I'm working on the html file and my Italian.js and will finish soon. 
Looks good to me! 
:+1:

**Pull request merged**
